#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ -x /sbin/dmraid ]; then
	force_load dm-mod
	force_load dm-mirror
	force_load dm-raid45
	copy_exec /sbin/dmraid sbin
	copy_exec /sbin/dmraid-activate sbin
	if [ -f /etc/udev/rules.d/85_dmraid.rules ]; then
		mkdir -p ${DESTDIR}/etc/udev/rules.d
		cp -p /etc/udev/rules.d/85_dmraid.rules ${DESTDIR}/etc/udev/rules.d
	fi
	if [ -f /etc/udev/rules.d/85-dmraid.rules ]; then
		mkdir -p ${DESTDIR}/etc/udev/rules.d
		cp -p /etc/udev/rules.d/85-dmraid.rules ${DESTDIR}/etc/udev/rules.d
	fi
	if [ -f /lib/udev/rules.d/85_dmraid.rules ]; then
		mkdir -p ${DESTDIR}/lib/udev/rules.d
		cp -p /lib/udev/rules.d/85_dmraid.rules ${DESTDIR}/lib/udev/rules.d
	fi
	if [ -f /lib/udev/rules.d/85-dmraid.rules ]; then
		mkdir -p ${DESTDIR}/lib/udev/rules.d
		cp -p /lib/udev/rules.d/85-dmraid.rules ${DESTDIR}/lib/udev/rules.d
	fi
fi

exit 0
