#!/bin/sh

# local-top script for dmraid.

PREREQS=""
prereqs()
{
	echo $PREREQS
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Activate any dmraid arrays that were not identified by udev and vol_id.

for dev in $(dmraid -r -c); do
	dmraid-activate $(basename $dev)
done
